apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: focalboard
  name: focalboard
  namespace: focalboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: focalboard
  template:
    metadata:
      labels:
        app: focalboard
    spec:
      initContainers:
      - name: chmod-er
        image: busybox:latest
        command:
        - /bin/chown
        - nobody
        - /data
        volumeMounts:
          - mountPath: /data
            name: focalboard-volume
      containers:
        - image: mattermost/focalboard:latest
          imagePullPolicy: Always
          name: focalboard
          ports:
          - containerPort: 8000
            name: http-focalboard
          volumeMounts:
          - mountPath: /data
            name: focalboard-volume
      volumes:
      - name: focalboard-volume
        hostPath:
          path: /var/services/focalboard
          type: DirectoryOrCreate
