apiVersion: v1
kind: Service
metadata:
  name: focalboard-service
  namespace: focalboard
status:
  loadBalancer: {}
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: http-focalboard
      nodePort: 30889
  selector:
    app: focalboard
  type: NodePort
