#!/usr/bin/env python3
# addons/python-demo-nginx/disable

import click
import os
import subprocess

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
SERVICE_NAME = "focalboard"

@click.command()
def main():
    click.echo(f"Disabling {SERVICE_NAME}")
    subprocess.check_call([
        KUBECTL, "delete", "namespace", SERVICE_NAME
    ])
    click.echo(f"Disabled {SERVICE_NAME}")

if __name__ == "__main__":
    main()
