#!/usr/bin/env python3
# addons/python-hello-k8s/enable

import os
import subprocess

import click

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
SERVICE_NAME = "focalboard"
MANIFESTS = f"addons/{SERVICE_NAME}/kubernetes"

@click.command()
def main():
    """
    This function will enable focalboard.

    It will create:
        - a namespace
        - a deployment
        - a service
    """
    click.echo(f"Enabling {SERVICE_NAME}")
    click.echo(f"osgetcwd(): {os.getcwd()}")
    try:
        subprocess.check_call([
            KUBECTL, "create", "namespace", SERVICE_NAME,
        ])
    except subprocess.CalledProcessError:
        click.echo(f"Enabling {SERVICE_NAME}")
        
    subprocess.check_call([
        KUBECTL, "apply", "-f", f"{MANIFESTS}/deployment.yaml",
    ])
    subprocess.check_call([
        KUBECTL, "apply", "-f", f"{MANIFESTS}/service.yaml",
    ])
    
    click.echo(f"Enabled {SERVICE_NAME}")

if __name__ == "__main__":
    main()
