#!/usr/bin/env python3
# addons/python-hello-k8s/enable

import os
import subprocess

import click

KUBECTL = os.path.expandvars("$SNAP/microk8s-kubectl.wrapper")
SERVICE_NAME = "focalboard"

@click.command()
def main():
    """
    This function will enable focalboard.

    """
    click.echo(f"Enabling {SERVICE_NAME}")
    click.echo(f"osgetcwd(): {os.getcwd()}")
    try:
        subprocess.check_call([
            KUBECTL, "create", "namespace", SERVICE_NAME,
        ])
    except subprocess.CalledProcessError:
        pass
        
    subprocess.check_call([
        KUBECTL, "apply", "-f", f"{SERVICE_NAME}/kubernetes/deployment.yaml",
    ])
    subprocess.check_call([
        KUBECTL, "apply", "-f", f"{SERVICE_NAME}kubernetes/service.yaml",
    ])
    
    click.echo(f"Enabled {SERVICE_NAME}")

if __name__ == "__main__":
    main()
